### PR TITLE
node-int64 improvements

### PR DESCRIPTION
**Pull request by nuggetwheat**
Hello,

Please consider pulling the associate commits.  They provide the following:

1. Enable support for instanceof
2. Added a compare() method to compare an Int64 with another

Thanks!

- Doug

### CODE REVIEW

**Comment by broofa** [comment]
@nuggetwheat - Thanks for contributing!  Can you please add tests for both `instanceof` and `compare` functionality to `test.js`?  Thanks!

**Comment by nuggetwheat** [comment]
Hey Robert,  Sure, no problem!  In writing the test for compare, I realized that it just does a simple lexicographical comparison of the bytes, which is probably not what people would expect.  I'll change it so that it compares the actual integers.

**Comment by nuggetwheat** [comment]
Hi Robert, I added the unit tests.  I also added a convenience method 'equals' for symmetry with the methods of the Buffer class.  Please let me know if it looks ok.  Feel free to squash them down to a single commit.

**Comment by broofa** [comment]
`npm publish`'ed as v0.4.0

**Comment by nuggetwheat** [comment]
Excellent!

**Pull request merged**
